<!-- beginning of error -->
<div class="row">
	<div class="small-12 columns center">
		<h1>Unsupported Browser</h1>
		<p>Your browser is unsupported and needs to be updated to ensure that this application runs properly.
		</p>
		<p>
			Detected Browser - <?= $_SESSION['browser']." ".$_SESSION['browser_version']; ?><br>
			Minimum Required - <?= $_SESSION['browser']." ".$this->params['browser'][ $_SESSION['browser'] ]; ?> or greater
		</p>
	</div>
</div>
<!-- end of error -->