<!DOCTYPE html>

<html lang="<?= $this->language; ?>">
<head>

<meta name="author" content="Dexter Atom Oddwick">
<meta name="copyright" content="Dexter Oddwick. Copyright (c) 2005-<?= date('Y', time()); ?>">
<meta name="git" content="www.github.com/oddwick/nerb">
<!-- HTTP-equiv -->
<meta http-equiv="content-type" content="text/html; charset=<?= $this->charset; ?>">
<?PHP 
	foreach( $this->http_equiv as $key => $content ){
		if ($content){
			echo '<meta http-equiv="'.$key.'" content="'.$content.'" />'.PHP_EOL;
		}
	}
?>

<!-- Set the viewport width to device width for mobile -->
<meta name="viewport" content="<?= $this->viewport; ?>" />

<!-- Page Icons -->
<?PHP 
	foreach( $this->icon as $key => $content ){
		if ($content){
			echo '<link rel='.$content.' />'.PHP_EOL;
		}
	}
?>

<!-- Link Rel-->
<?PHP 
	foreach( $this->rel as $key => $content ){
		if ($content){
			echo '<link rel="'.$key.'" href="'.$content.'" />'.PHP_EOL;
		}
	}
?>

<!-- Metadata -->
<?PHP 
	foreach( $this->meta as $key => $content ){
		if ($content){
			echo '<meta name="'.$key.'" content="'.$content.'" />'.PHP_EOL;
		}
	}
?>

<title><?= $this->title; ?></title>

<!-- Included CSS Files -->
<?PHP 
	foreach( $this->style as $content ){
		if ($content){
			echo '<link rel="stylesheet" type="text/css" href="'.$content.'" />'.PHP_EOL;
		}
	}
?>


<!-- Included Script Files -->
<?PHP 
	if( $this->scripts_in_header ){
		foreach( $this->script as $content ){
			if ($content){
				// this one contains text/javascript, but wont pass validation
				//echo '<script '.( $this["asynch_scripts"] ? "async " : NULL ).'type="text/javascript" src="'.$link.'"></script>'.PHP_EOL;
				echo '<script '.( $this->asynch_scripts ? "async " : NULL ).' src="'.$content.'"></script>'.PHP_EOL;
			}
		}
	}
?>

<!-- Set Base -->
<?PHP if( $this->base ){ ?>
<base href="<?= $this->base;  ?>" />
<?PHP } ?>
<!-- IE Fix for HTML5 Tags -->
<!--[if lt IE 9]>
		<script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>
<body>
<!-- begin content injection -->